import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {registerCustomerRoutes,customerDocument,isPublicKey} from './customer-routes.mjs';
const alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222';
const key='sb_publishable_TESTONLY',token='Bearer '+ 'a'.repeat(30);
async function server(env,fn,run){const app=express();registerCustomerRoutes(app,{json:express.json,env,fetchImpl:fn});const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));try{await run('http://127.0.0.1:'+s.address().port);}finally{await new Promise(r=>s.close(r));}}
const env={CUSTOMER_ACCOUNTS_ENABLED:'true',SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:key};const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
test('test-order retries insert once and never write paid records',async()=>{let row,inserts=0;await server(env,async(url,o)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice,email:'test@example.invalid'});assert.ok(url.includes('amcinova_test_orders'));if(o.method==='POST'){row=JSON.parse(o.body);inserts++;assert.equal(row.user_id,alice);assert.equal(row.status,'TEST');return response([row]);}assert.ok(url.includes('user_id=eq.'+alice));return response(row?[row]:[]);},async url=>{const body={id:bob,selected:['promotie','admaker'],method:'once',terms:6,quoteService:0,siteService:0,user_id:bob,status:'paid'};for(let i=0;i<2;i++){const r=await fetch(url+'/api/customer/test-orders',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);assert.equal((await r.json()).order.status,'TEST');}assert.equal(inserts,1);assert.equal((await fetch(url+'/api/admin/test-orders',{headers:{Authorization:token}})).status,401);});});
test('disabled account rollout cannot access auth or database',async()=>{await server({},()=>assert.fail('network'),async url=>{assert.equal((await fetch(url+'/api/customer/me')).status,503);assert.equal((await(await fetch(url+'/api/customer/config')).json()).enabled,false);});});
test('service key is never exposed as public config',()=>{assert.equal(isPublicKey('sb_secret_test'),false);assert.equal(isPublicKey('x.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.x'),false);assert.equal(isPublicKey(key),true);});
test('missing and rejected bearer tokens cannot reach customer data',async()=>{let calls=0;await server(env,async(url)=>{calls++;assert.ok(url.endsWith('/auth/v1/user'));return response({},401);},async url=>{assert.equal((await fetch(url+'/api/customer/me')).status,401);assert.equal(calls,0);assert.equal((await fetch(url+'/api/customer/me',{headers:{Authorization:token}})).status,401);assert.equal(calls,1);});});
test('document reads always filter verified owner even with forged query user',async()=>{await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('user_id=eq.'+alice));assert.ok(!url.includes(bob));assert.equal(opts.headers.Authorization,token);assert.equal(opts.headers.apikey,key);return response([]);},async url=>{const r=await fetch(url+'/api/customer/documents?product=sitebuilder&user_id='+bob,{headers:{Authorization:token}});assert.equal(r.status,200);});});
test('another customer document gives 404 with owner filter',async()=>{await server(env,async(url)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('user_id=eq.'+alice));return response([]);},async url=>{assert.equal((await fetch(url+'/api/customer/documents/'+bob,{headers:{Authorization:token}})).status,404);});});
test('document creation ignores spoofed owner and propagates RLS rejection',async()=>{await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('customer_access'))return response([{status:'active',source:'trial'}]);assert.equal(JSON.parse(opts.body).user_id,alice);return response({},403);},async url=>{const r=await fetch(url+'/api/customer/documents',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({user_id:bob,product:'sitebuilder',projectId:alice,revision:1,name:'TEST account',payload:{fields:{}}})});assert.equal(r.status,403);});});
test('invalid product, revision and payload rejected',()=>{const base={product:'sitebuilder',projectId:alice,revision:1,name:'TEST',payload:{}};for(const changes of [{product:'admin'},{revision:0},{payload:[]},{projectId:'x'},{name:''}])assert.throws(()=>customerDocument({...base,...changes},alice));assert.equal(customerDocument({...base,user_id:bob},alice).user_id,alice);});

for(const [name,access,paid,status] of [
 ['sitebuilder purchase allowed',{status:'active',source:'purchase',purchase_id:alice},true,200],
 ['unpaid purchase denied',{status:'active',source:'purchase',purchase_id:alice},false,403],
 ['revoked denied',{status:'revoked',source:'manual'},false,403],
 ['expired denied',{status:'active',source:'trial',expires_at:'2020-01-01'},false,403],
 ['missing denied',null,false,403],
 ['trial allowed',{status:'active',source:'trial'},false,200]
])test(name,async()=>{await server(env,async url=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('customer_access'))return response(access?[access]:[]);if(url.includes('customer_purchases'))return response(paid?[{id:alice,verified_at:'2026-10-07'}]:[]);assert.fail(url);},async url=>{assert.equal((await fetch(url+'/api/customer/access/sitebuilder',{headers:{Authorization:token}})).status,status);});});
test('quote-only access never grants sitebuilder or AI',async()=>{await server(env,async url=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('product_code=eq.offertetool'))return response([{status:'active',source:'manual'}]);if(url.includes('customer_access'))return response([]);assert.fail(url);},async url=>{assert.equal((await fetch(url+'/api/customer/access/offertetool',{headers:{Authorization:token}})).status,200);assert.equal((await fetch(url+'/api/customer/access/sitebuilder',{headers:{Authorization:token}})).status,403);assert.equal((await fetch(url+'/api/customer/ai/generate',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({task:'site',fields:{}})})).status,403);});});

test('selection stores only verified owner preferences and cannot grant access',async()=>{let stored=false;await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('amcinova_customer_profiles'));assert.equal(opts.headers.Prefer,'resolution=merge-duplicates,return=representation');assert.deepEqual(JSON.parse(opts.body),{user_id:alice,selected_products:['planner','admaker']});stored=true;return response([]);},async url=>{const r=await fetch(url+'/api/customer/selection',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({user_id:bob,selected:['planner','admaker','planner'],status:'paid'})});assert.equal(r.status,200);assert.ok(stored);});});
test('selection rejects unknown products before database write',async()=>{await server(env,async url=>{assert.ok(url.endsWith('/auth/v1/user'));return response({id:alice});},async url=>{for(const selected of [['admin'],null,'sitebuilder']){const r=await fetch(url+'/api/customer/selection',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({selected})});assert.equal(r.status,400);}});});
test('saved selection is loaded for verified owner only',async()=>{await server(env,async url=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('user_id=eq.'+alice));assert.ok(!url.includes(bob));return response([{selected_products:['shophulp']}]);},async url=>{const r=await fetch(url+'/api/customer/selection?user_id='+bob,{headers:{Authorization:token}});const d=await r.json();assert.deepEqual(d.selected,['shophulp']);assert.equal(d.catalog.length,7);assert.equal(d.bundles.length,3);});});

test('free website plan uses verified owner and preserves unrelated profile fields',async()=>{let saved;await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('amcinova_customer_profiles'));if(opts.method==='POST'){saved=JSON.parse(opts.body);assert.deepEqual(Object.keys(saved).sort(),['user_id','website_plan']);assert.equal(saved.user_id,alice);return response([saved]);}assert.ok(url.includes('user_id=eq.'+alice));return response([{website_plan:saved.website_plan}]);},async url=>{const plan={name:'TEST plan',audience:'vakman',offer:'website',style:'blauw',pages:'contact',action:'aanvraag',user_id:bob};const r=await fetch(url+'/api/customer/website-plan',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({plan,user_id:bob})});assert.equal(r.status,200);assert.equal(saved.website_plan.user_id,undefined);const d=await(await fetch(url+'/api/customer/website-plan?user_id='+bob,{headers:{Authorization:token}})).json();assert.equal(d.plan.name,'TEST plan');});});
test('invalid website plan never reaches database',async()=>{await server(env,async url=>{assert.ok(url.endsWith('/auth/v1/user'));return response({id:alice});},async url=>{for(const plan of [null,[],{name:''},{name:'a'.repeat(2001)}])assert.equal((await fetch(url+'/api/customer/website-plan',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({plan})})).status,400);});});
test('tester signup uses verified identity and only writes interest field',async()=>{let saved;await server(env,async(url,o)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice,email:'own@example.invalid'});assert.ok(url.includes('amcinova_customer_profiles'));if(o.method==='POST'){saved=JSON.parse(o.body);assert.deepEqual(Object.keys(saved).sort(),['tester_application','user_id']);assert.equal(saved.user_id,alice);return response([saved]);}assert.ok(url.includes('user_id=eq.'+alice));return response([saved]);},async url=>{const r=await fetch(url+'/api/customer/tester-application',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({product:'sitebuilder',goal:'TEST',contactConsent:true,user_id:bob,email:'forged',status:'active'})});assert.equal(r.status,200);assert.equal(saved.tester_application.email,'own@example.invalid');assert.equal(saved.tester_application.status,'interest');assert.equal((await fetch(url+'/api/customer/tester-application',{headers:{Authorization:token}})).status,200);assert.equal((await fetch(url+'/api/admin/tester-applications',{headers:{Authorization:token}})).status,401);});});
test('expired trial retains own document read but blocks new project writes and AI',async()=>{await server(env,async(url)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('amcinova_customer_access'))return response([{status:'active',source:'trial',expires_at:'2020-01-01T00:00:00Z'}]);if(url.includes('amcinova_customer_documents')){assert.ok(url.includes('user_id=eq.'+alice));return response([{id:bob,user_id:alice,product_code:'sitebuilder',payload:{text:'TEST own work'}}]);}assert.fail(url);},async url=>{const headers={Authorization:token,'Content-Type':'application/json'};const read=await fetch(url+'/api/customer/documents/'+bob,{headers});assert.equal(read.status,200);assert.equal((await read.json()).document.payload.text,'TEST own work');assert.equal((await fetch(url+'/api/customer/documents',{method:'POST',headers,body:JSON.stringify({product:'sitebuilder',projectId:alice,revision:1,name:'TEST expired',payload:{}})})).status,403);assert.equal((await fetch(url+'/api/customer/ai/generate',{method:'POST',headers,body:JSON.stringify({task:'site',fields:{}})})).status,403);});});

test('credit balance ignores forged customer and expired grants',async()=>{
 await server({...env,CUSTOMER_AI_CREDITS_ENABLED:'true'},async(url,o)=>{
  if(url.endsWith('/auth/v1/user'))return response({id:alice});
  assert.ok(url.includes('amcinova_ai_credit_grants?user_id=eq.'+alice));
  assert.ok(!url.includes(bob));assert.equal(o.headers.Authorization,token);assert.equal(o.headers.apikey,key);
  return response([{product_code:'sitebuilder',remaining:7,expires_at:null},{product_code:'sitebuilder',remaining:99,expires_at:'2020-01-01'}]);
 },async url=>{
  const r=await fetch(url+'/api/customer/credits?user_id='+bob,{headers:{Authorization:token}});
  assert.equal(r.status,200);const d=await r.json();assert.equal(d.balances.find(p=>p.product==='sitebuilder').remaining,7);assert.equal(d.topupEnabled,false);
 });
});
test('zero balance blocks AI provider and uses verified owner for reservation',async()=>{
 await server({...env,CUSTOMER_AI_CREDITS_ENABLED:'true',SUPABASE_SERVICE_ROLE_KEY:'TEST-server-only'},async(url,o)=>{
  if(url.endsWith('/auth/v1/user'))return response({id:alice});
  if(url.includes('amcinova_customer_access'))return response([{status:'active',source:'trial'}]);
  assert.ok(url.endsWith('/rpc/amcinova_credit_reserve'));const body=JSON.parse(o.body);
  assert.equal(body.p_user,alice);assert.equal(body.p_product,'sitebuilder');assert.match(body.p_request,/^[a-f0-9-]{36}$/);return response(false);
 },async url=>{
  const r=await fetch(url+'/api/customer/ai/generate',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({task:'site',fields:{},user_id:bob})});
  assert.equal(r.status,402);
 });
});
test('customer login cannot inspect admin credit history',async()=>{await server(env,()=>assert.fail('network'),async url=>{assert.equal((await fetch(url+'/api/admin/ai-credits/'+bob,{headers:{Authorization:token}})).status,401);});});
test('extra credit test request is idempotent and never changes balance',async()=>{
 let row,inserts=0;await server({...env,CUSTOMER_AI_CREDITS_ENABLED:'true'},async(url,o)=>{
  if(url.endsWith('/auth/v1/user'))return response({id:alice});
  if(url.includes('amcinova_customer_access'))return response([{status:'active',source:'trial'}]);
  assert.ok(url.includes('amcinova_ai_topup_requests'));
  if(o.method==='POST'){row=JSON.parse(o.body);inserts++;assert.equal(row.user_id,alice);assert.equal(row.status,'TEST');return response([row]);}
  assert.ok(url.includes('user_id=eq.'+alice));return response(row?[row]:[]);
 },async url=>{
  const send=units=>fetch(url+'/api/customer/credits/test-request',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({id:bob,product:'sitebuilder',units,user_id:bob,status:'paid'})});
  for(let i=0;i<2;i++)assert.equal((await send(25)).status,200);
  assert.equal((await send(100)).status,409);assert.equal(inserts,1);
 });
});
test('invalid test pack is rejected before access or database write',async()=>{
 await server({...env,CUSTOMER_AI_CREDITS_ENABLED:'true'},async url=>{assert.ok(url.endsWith('/auth/v1/user'));return response({id:alice});},async url=>{
  const r=await fetch(url+'/api/customer/credits/test-request',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({id:bob,product:'sitebuilder',units:999})});assert.equal(r.status,400);
 });
});
