import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import {registerCustomerRoutes,customerDocument,isPublicKey} from './customer-routes.mjs';
const alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222';
const key='sb_publishable_TESTONLY',token='Bearer '+ 'a'.repeat(30);
async function server(env,fn,run){const app=express();registerCustomerRoutes(app,{json:express.json,env,fetchImpl:fn});const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));try{await run('http://127.0.0.1:'+s.address().port);}finally{await new Promise(r=>s.close(r));}}
const env={CUSTOMER_ACCOUNTS_ENABLED:'true',SUPABASE_URL:'https://test.invalid',SUPABASE_ANON_KEY:key};const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
test('disabled account rollout cannot access auth or database',async()=>{await server({},()=>assert.fail('network'),async url=>{assert.equal((await fetch(url+'/api/customer/me')).status,503);assert.equal((await(await fetch(url+'/api/customer/config')).json()).enabled,false);});});
test('service key is never exposed as public config',()=>{assert.equal(isPublicKey('sb_secret_test'),false);assert.equal(isPublicKey('x.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.x'),false);assert.equal(isPublicKey(key),true);});
test('missing and rejected bearer tokens cannot reach customer data',async()=>{let calls=0;await server(env,async(url)=>{calls++;assert.ok(url.endsWith('/auth/v1/user'));return response({},401);},async url=>{assert.equal((await fetch(url+'/api/customer/me')).status,401);assert.equal(calls,0);assert.equal((await fetch(url+'/api/customer/me',{headers:{Authorization:token}})).status,401);assert.equal(calls,1);});});
test('document reads always filter verified owner even with forged query user',async()=>{await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('user_id=eq.'+alice));assert.ok(!url.includes(bob));assert.equal(opts.headers.Authorization,token);assert.equal(opts.headers.apikey,key);return response([]);},async url=>{const r=await fetch(url+'/api/customer/documents?product=sitebuilder&user_id='+bob,{headers:{Authorization:token}});assert.equal(r.status,200);});});
test('another customer document gives 404 with owner filter',async()=>{await server(env,async(url)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});assert.ok(url.includes('user_id=eq.'+alice));return response([]);},async url=>{assert.equal((await fetch(url+'/api/customer/documents/'+bob,{headers:{Authorization:token}})).status,404);});});
test('document creation ignores spoofed owner and propagates RLS rejection',async()=>{await server(env,async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('customer_access'))return response([{status:'active',source:'trial'}]);assert.equal(JSON.parse(opts.body).user_id,alice);return response({},403);},async url=>{const r=await fetch(url+'/api/customer/documents',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({user_id:bob,product:'sitebuilder',projectId:alice,revision:1,name:'TEST account',payload:{fields:{}}})});assert.equal(r.status,403);});});
test('invalid product, revision and payload rejected',()=>{const base={product:'sitebuilder',projectId:alice,revision:1,name:'TEST',payload:{}};for(const changes of [{product:'admin'},{revision:0},{payload:[]},{projectId:'x'},{name:''}])assert.throws(()=>customerDocument({...base,...changes},alice));assert.equal(customerDocument({...base,user_id:bob},alice).user_id,alice);});

for(const [name,access,paid,status] of [
 ['sitebuilder purchase allowed',{status:'active',source:'purchase',purchase_id:alice},true,200],
 ['unpaid purchase denied',{status:'active',source:'purchase',purchase_id:alice},false,403],
 ['revoked denied',{status:'revoked',source:'manual'},false,403],
 ['expired denied',{status:'active',source:'trial',expires_at:'2020-01-01'},false,403],
 ['missing denied',null,false,403],
 ['trial allowed',{status:'active',source:'trial'},false,200]
])test(name,async()=>{await server(env,async url=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('customer_access'))return response(access?[access]:[]);if(url.includes('customer_purchases'))return response(paid?[{id:alice,verified_at:'2026-10-07'}]:[]);assert.fail(url);},async url=>{assert.equal((await fetch(url+'/api/customer/access/sitebuilder',{headers:{Authorization:token}})).status,status);});});
test('quote-only access never grants sitebuilder or AI',async()=>{await server(env,async url=>{if(url.endsWith('/auth/v1/user'))return response({id:alice});if(url.includes('product_code=eq.offertetool'))return response([{status:'active',source:'manual'}]);if(url.includes('customer_access'))return response([]);assert.fail(url);},async url=>{assert.equal((await fetch(url+'/api/customer/access/offertetool',{headers:{Authorization:token}})).status,200);assert.equal((await fetch(url+'/api/customer/access/sitebuilder',{headers:{Authorization:token}})).status,403);assert.equal((await fetch(url+'/api/customer/ai/generate',{method:'POST',headers:{Authorization:token,'Content-Type':'application/json'},body:JSON.stringify({task:'site',fields:{}})})).status,403);});});
