import test from 'node:test';import assert from 'node:assert/strict';
import {verifyProblems,verifySolution,researchDigital} from './digital-products.mjs';
import {generateAgent} from './agent-ai.mjs';
const problems=Array.from({length:10},(_,i)=>({title:'Probleem '+(i+1),audience:'Testdoelgroep',problem:'Een concreet testprobleem',evidence:'Een bron beschrijft dit probleem; betalingsbereidheid onbekend.',source:'https://example.org/problems/'+i}));
const raw={summary:'Tien testproblemen',problems};
const response={status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:problems.map(p=>({url:p.source}))}},{content:[{type:'output_text',text:JSON.stringify(raw)}]}]};
const solution={name:'Testwerkboek',format:'PDF-werkboek',promise:'Meer overzicht als beoogd resultaat',summary:'Een concept voor het gekozen probleem',contents:Array.from({length:3},(_,i)=>({title:'Onderdeel '+i,description:'Een concrete opdracht'})),sample:'Een bruikbaar ingevuld voorbeeld',buildSteps:['Schrijf het werkboek'],validation:['Laat drie gebruikers de opdracht uitvoeren'],limitations:['Nog geen afgewerkt downloadbestand']};
const output=raw=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(raw)}]}]});
test('exactly ten sourced distinct options; no padded or fabricated sources',()=>{assert.equal(verifyProblems(raw,response).problems.length,10);assert.throws(()=>verifyProblems({...raw,problems:problems.slice(0,9)},response),/tien/);assert.throws(()=>verifyProblems({...raw,problems:[problems[0],...problems.slice(0,9)]},response),/herhaling/);assert.throws(()=>verifyProblems({...raw,problems:problems.map((p,i)=>i? p:{...p,source:'https://invented.example/test'})},response),/bron/);assert.throws(()=>verifyProblems(raw,{output:[]}),/webbronnen/);});
test('problem route performs web research without profile or hidden saved state',async()=>{let called=false;const result=await generateAgent({task:'advice',fields:{'research-mode':'digital-problems','builder-shop-sector-other':'studenten','profile-name':'UNRELATED','builder-digital-state':'PRIVATE'}},{env:{OPENAI_API_KEY:'fake'},fetchImpl:async(url,options)=>{called=true;const body=JSON.parse(options.body);assert.equal(body.tool_choice,'required');assert.equal(body.store,false);assert.ok(body.input.includes('studenten'));assert.ok(!body.input.includes('PRIVATE'));assert.ok(!body.input.includes('UNRELATED'));return{ok:true,json:async()=>response};}});assert.ok(called);assert.equal(result.kind,'digital-problems');});
test('solution follows chosen problem, omits web claims, validates complete plan',async()=>{const chosen=problems[7];const result=await researchDigital({'research-mode':'digital-solution','digital-problem':JSON.stringify(chosen)},{env:{OPENAI_API_KEY:'fake'},fetchImpl:async(url,options)=>{const body=JSON.parse(options.body);assert.equal(JSON.parse(body.input).selectedProblem.title,chosen.title);assert.equal(body.tools,undefined);return{ok:true,json:async()=>output(solution)};}});assert.equal(result.problem.title,chosen.title);assert.equal(result.solution.sample,solution.sample);assert.throws(()=>verifySolution({...solution,contents:[]},chosen),/volledig/);assert.throws(()=>verifySolution({...solution,validation:[]},chosen),/vervolgstappen/);});
test('bad choice, incomplete result and provider failure are explicit',async()=>{await assert.rejects(researchDigital({'research-mode':'digital-solution','digital-problem':'{}'}),/Kies/);await assert.rejects(researchDigital({},{fetchImpl:async()=>({ok:true,json:async()=>({status:'incomplete'})})}),/afgerond/);await assert.rejects(researchDigital({},{fetchImpl:async()=>({ok:false})}),/niet beschikbaar/);});

test("previously explored titles are rejected",()=>{assert.throws(()=>verifyProblems(raw,response,[problems[2].title]),/eerder onderwerp/);});
