import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyOffer} from './digital-offer.mjs';
import {researchDigital} from './digital-products.mjs';
const urls=['https://www.amazon.nl/dp/EXAMPLE','https://example.org/workbook'];
const tier={name:'Voorbeeld',outcome:'Klein concreet resultaat',deliverables:['Een uitgewerkte opdracht'],addedValue:'Direct invulbaar',priceHypothesis:'Nog te toetsen'};
const fixture=()=>({name:'Werkboek',format:'PDF',promise:'Meer overzicht',summary:'Voorstel',contents:[1,2,3].map(i=>({title:'Stap '+i,description:'Opdracht'})),sample:'Concreet voorbeeld',buildSteps:['Uitwerken'],validation:['Vraagtest'],limitations:['Concept'],market:{summary:'Twee productpagina’s',amazonNote:'Een gedrukt boek gevonden',competitors:urls.map(source=>({seller:'Aanbieder',name:'Vergelijkbaar boek',format:'Gedrukt boek',contents:'Opdrachten',pricingStatus:'priced',priceObserved:'EUR 12',reviewFindings:'Niet beschikbaar',reviewSource:'',difference:'Ander formaat',source})),freeAlternatives:[]},decision:{verdict:'paid_candidate',rationale:'Alleen te testen',distinctiveValue:'Bewerkbare opdrachten',validationTest:'Vijf gesprekken',stopCriteria:'Geen behoefte'},tiers:{free:{...tier},standard:{...tier},premium:{...tier}},funnel:[1,2,3].map(i=>({stage:'Stap '+i,offer:'Voorstel',nextStep:'Met toestemming'}))});
test('market facts retain observed URLs and date; absent Amazon is explicit',()=>{const result=verifyOffer(fixture(),urls);assert.equal(result.market.amazonStatus,'Productpagina gevonden');assert.ok(Date.parse(result.market.checkedAt));assert.equal(result.tiers.free.priceHypothesis,'Gratis');const other=fixture();other.market.competitors=other.market.competitors.slice(1);const limited=verifyOffer(other,urls);assert.equal(limited.market.amazonStatus,'Geen Amazon-productpagina bevestigd');assert.equal(limited.decision.verdict,'insufficient_evidence');});
test('invented sources, missing tiers and missing stop criteria are rejected',()=>{const fake=fixture();fake.market.competitors[0].source='https://invented.example/product';assert.throws(()=>verifyOffer(fake,urls),/bron/);const missing=fixture();delete missing.tiers.premium;assert.throws(()=>verifyOffer(missing,urls),/volledig/);const noStop=fixture();noStop.decision.stopCriteria='';assert.throws(()=>verifyOffer(noStop,urls),/volledig/);});
test('selected solution researches competitors before constructing its ladder',async()=>{let calls=0,signal;const chosen={title:'Probleem',audience:'Doelgroep',problem:'Concreet probleem',evidence:'Probleemsignaal',source:'https://example.org/problem'};const result=await researchDigital({'research-mode':'digital-solution','digital-problem':JSON.stringify(chosen),'profile-name':'PRIVATE'},{env:{OPENAI_API_KEY:'secret'},fetchImpl:async(url,opts)=>{calls++;const body=JSON.parse(opts.body);assert.equal(JSON.parse(body.input).selectedProblem.title,chosen.title);assert.ok(!body.input.includes('PRIVATE'));if(calls===1){signal=opts.signal;assert.match(body.instructions,/Amazon/);assert.equal(body.tool_choice,'required');return{ok:true,json:async()=>({status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:urls.map(url=>({url}))}},{content:[{type:'output_text',text:'Twee vergelijkbare producten gevonden; prijzen onbekend.'}]}]})};}assert.equal(opts.signal,signal);assert.equal(body.tools,undefined);assert.deepEqual(body.text.format.schema.properties.market.properties.competitors.items.properties.source.enum,urls);return{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(fixture())}]}]})};}});assert.equal(calls,2);assert.equal(result.kind,'digital-solution');assert.equal(result.solution.offerVersion,1);});

test('free and unpriced alternatives do not establish a paid opportunity',()=>{const raw=fixture();raw.market.competitors.forEach(c=>{c.pricingStatus='free';c.reviewFindings='Unsupported praise';});const checked=verifyOffer(raw,urls);assert.equal(checked.decision.verdict,'insufficient_evidence');assert.match(checked.market.competitors[0].reviewFindings,/Geen klantreviews/);});
