import test from 'node:test';import assert from 'node:assert/strict';
import {verifyProblems,verifySolution,researchDigital} from './digital-products.mjs';
import {generateAgent} from './agent-ai.mjs';
const problems=Array.from({length:10},(_,i)=>({title:'Probleem '+(i+1),audience:'Testdoelgroep',problem:'Een concreet testprobleem',evidence:'Een bron beschrijft dit probleem; betalingsbereidheid onbekend.',source:'https://example.org/problems/'+i}));
const raw={summary:'Tien testproblemen',problems};
const response={status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:problems.map(p=>({url:p.source}))}},{content:[{type:'output_text',text:JSON.stringify(raw)}]}]};
const solution={name:'Testwerkboek',format:'PDF-werkboek',promise:'Meer overzicht als beoogd resultaat',summary:'Een concept voor het gekozen probleem',contents:Array.from({length:3},(_,i)=>({title:'Onderdeel '+i,description:'Een concrete opdracht'})),sample:'Een bruikbaar ingevuld voorbeeld',buildSteps:['Schrijf het werkboek'],validation:['Laat drie gebruikers de opdracht uitvoeren'],limitations:['Nog geen afgewerkt downloadbestand']};
const output=raw=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(raw)}]}]});
test('exactly ten sourced distinct options; no padded or fabricated sources',()=>{assert.equal(verifyProblems(raw,response).problems.length,10);assert.throws(()=>verifyProblems({...raw,problems:problems.slice(0,9)},response),/tien/);assert.throws(()=>verifyProblems({...raw,problems:[problems[0],...problems.slice(0,9)]},response),/herhaling/);assert.throws(()=>verifyProblems({...raw,problems:problems.map((p,i)=>i? p:{...p,source:'https://invented.example/test'})},response),/bron/);assert.throws(()=>verifyProblems(raw,{output:[]}),/webbronnen/);});
test('problem route performs web research without profile or hidden saved state',async()=>{let called=0;const result=await generateAgent({task:'advice',fields:{'research-mode':'digital-problems','builder-shop-sector-other':'studenten','profile-name':'UNRELATED','builder-digital-state':'PRIVATE'}},{env:{OPENAI_API_KEY:'fake'},fetchImpl:async(url,options)=>{called++;const body=JSON.parse(options.body);assert.equal(body.tool_choice,called===1?'required':undefined);if(called===1)assert.equal(body.text,undefined);else assert.equal(body.text.format.schema.properties.problems.minItems,10);assert.equal(body.store,false);assert.ok(body.input.includes('studenten'));assert.ok(!body.input.includes('PRIVATE'));assert.ok(!body.input.includes('UNRELATED'));return{ok:true,json:async()=>response};}});assert.equal(called,2);assert.equal(result.kind,'digital-problems');});
test('solution validates complete base product',()=>{const chosen=problems[7];assert.equal(verifySolution(solution,chosen).problem.title,chosen.title);assert.throws(()=>verifySolution({...solution,contents:[]},chosen),/volledig/);assert.throws(()=>verifySolution({...solution,validation:[]},chosen),/vervolgstappen/);});

test('bad choice, incomplete result and provider failure are explicit',async()=>{await assert.rejects(researchDigital({'research-mode':'digital-solution','digital-problem':'{}'}),/Kies/);await assert.rejects(researchDigital({},{fetchImpl:async()=>({ok:true,json:async()=>({status:'incomplete'})})}),/afgerond/);await assert.rejects(researchDigital({},{fetchImpl:async()=>({ok:false})}),/niet beschikbaar/);});

test("previously explored titles are rejected",()=>{assert.throws(()=>verifyProblems(raw,response,[problems[2].title]),/eerder onderwerp/);});

test('repairs an invalid draft once, retaining verified evidence and the total deadline',async()=>{let calls=0,signal;const invalid={...raw,problems:problems.slice(0,9)};const result=await researchDigital({},{env:{OPENAI_API_KEY:'secret-not-in-input'},fetchImpl:async(url,options)=>{calls++;const body=JSON.parse(options.body);if(calls===1){signal=options.signal;return{ok:true,json:async()=>({...response,output:[response.output[0],...output(invalid).output]})};}assert.equal(options.signal,signal);const input=JSON.parse(body.input);if(calls===2)return{ok:true,json:async()=>output(invalid)};assert.equal(input.rejectedDraft.problems.length,9);assert.equal(input.verifiedSourceUrls.length,10);assert.ok(!body.input.includes('secret-not-in-input'));return{ok:true,json:async()=>output(raw)};}});assert.equal(calls,3);assert.equal(result.problems.length,10);});

test('repair still rejects fabricated sources and never retries indefinitely',async()=>{let calls=0;const invalid={...raw,problems:problems.map(p=>({...p,source:'https://invented.example/no-evidence'}))};await assert.rejects(researchDigital({},{fetchImpl:async()=>{calls++;return{ok:true,json:async()=>({...response,output:[response.output[0],...output(invalid).output]})};}}),/bron/);assert.equal(calls,3);});
