import test from 'node:test';import assert from 'node:assert/strict';
import {verifyResearch,researchShop,publicUrl} from './shop-research.mjs';
const url='https://supplier.example/catalogue',supplier={name:'Fixture supplier',type:'dropship',url,reason:'Past',terms:'Niet bevestigd'},product={name:'Fixture product',description:'Voorstel',url,supplier:'Fixture supplier'};
const raw={summary:'Test',suppliers:[supplier],products:[product],limitations:[]};
const response={status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:[{url}]}},{content:[{type:'output_text',text:JSON.stringify(raw)}]}]};
test('only searched sources survive; duplicates and invented sources are excluded',()=>{const r=verifyResearch({...raw,suppliers:[supplier,supplier,{...supplier,url:'https://invented.example'}],products:[product,{...product,url:'javascript:alert(1)'}]},response);assert.equal(r.suppliers.length,1);assert.equal(r.products.length,1);assert.match(r.limitations.join(" "),/3 leverancierskandidaten.*1 leveranciers/);assert.throws(()=>verifyResearch(raw,{output:[]}),/webzoekopdracht/);});
test('research uses web search, keeps profile and credentials out of research input',async()=>{const r=await researchShop({'builder-shop-sector':'Boeken','builder-links':url,'profile-prices':'private','builder-shop-state':'private'},{env:{OPENAI_API_KEY:'secret'},fetchImpl:async(u,o)=>{const b=JSON.parse(o.body);assert.equal(b.tools[0].type,'web_search');assert.equal(b.tool_choice,'required');assert.equal(b.store,false);assert.ok(!b.input.includes('private'));assert.ok(!b.input.includes('secret'));return {ok:true,json:async()=>response};}});assert.equal(r.suppliers.length,1);});
test('bad URLs, incomplete responses and provider errors fail safely',async()=>{for(const u of ['http://example.com','https://127.0.0.1','https://a:b@example.com','https://host.internal','javascript:alert(1)'])assert.equal(publicUrl(u),'');await assert.rejects(researchShop({},{env:{OPENAI_API_KEY:'fake'},fetchImpl:async()=>({ok:false})}),/niet beschikbaar/);await assert.rejects(researchShop({},{env:{OPENAI_API_KEY:'fake'},fetchImpl:async()=>({ok:true,json:async()=>({status:'incomplete'})})}),/niet volledig/);});

test('publishers and manufacturers retained only with observed source',()=>{for(const type of ['publisher','manufacturer']){const r=verifyResearch({...raw,suppliers:[{...supplier,type}]},response);assert.equal(r.suppliers[0].type,type);}});


