(()=>{
 const api='https://api.amcinova.com',form=document.querySelector('#workbook'),status=document.querySelector('#status'),button=form.querySelector('button');let requestId=crypto.randomUUID(),busy=false,storedBody=null;
 async function waitFetch(url,options,onWait){const controller=new AbortController(),waitTimer=setTimeout(onWait,12000),timeout=setTimeout(()=>controller.abort(),120000);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(waitTimer);clearTimeout(timeout);}}
 form.proposal.addEventListener('change',()=>{document.querySelector('#help-label').hidden=!form.proposal.checked;});
 waitFetch(api+'/api/workbook/config',{cache:'no-store',credentials:'omit'},()=>{status.textContent='De server start mogelijk op. Dit kan een minuut of langer duren; blijf even wachten.';}).then(r=>r.json()).then(c=>{if(!c.enabled||c.delivery!=='email')throw Error();const u=new URL(c.privacyUrl);if(u.protocol!=='https:'||!['amcinova.com','agents.amcinova.com'].includes(u.hostname))throw Error();document.querySelector('#privacy').href=u.href;form.hidden=false;status.textContent='';}).catch(()=>{status.textContent='De werkboekbezorging is nog niet beschikbaar of de reactie duurt te lang. Ververs de pagina later opnieuw.';});
 form.addEventListener('submit',async event=>{
  event.preventDefault();if(busy||(!storedBody&&!form.reportValidity()))return;busy=true;button.disabled=true;status.textContent='Je aanvraag wordt verwerkt.';
  const body=storedBody||{requestId,name:form.elements.namedItem('name').value,email:form.elements.namedItem('email').value,proposal:form.proposal.checked,help:form.proposal.checked?form.help.value:''};let knownOutcome=false;
  try{
   const r=await waitFetch(api+'/api/workbook/request',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},()=>{status.textContent='De server start mogelijk op. Opslag en e-mailbezorging zijn nog niet bevestigd; blijf wachten.';}),data=await r.json();
   if(!r.ok||!data.saved){knownOutcome=[400,403,409,410,413].includes(r.status);if(r.status===409||r.status===410){requestId=crypto.randomUUID();storedBody=null;for(const field of form.querySelectorAll('input,textarea'))field.disabled=false;}throw Error(data.error||'De aanvraag kon niet worden bevestigd. Probeer opnieuw.');}
   knownOutcome=true;
   if(!data.emailAccepted){storedBody=body;status.textContent=data.deliveryStatus==='uncertain'?'Je aanvraag is opgeslagen. Of de maildienst de werkboekmail heeft geaccepteerd, is nog niet bevestigd. Dit vraagt controle door Amcinova; we versturen niet automatisch opnieuw.':'Je aanvraag is opgeslagen, maar de e-mailbezorging is nog niet bevestigd. Probeer later opnieuw.';button.textContent='Bezorgingsstatus opnieuw controleren';for(const field of form.querySelectorAll('input,textarea'))field.disabled=true;return;}
   status.textContent='Je aanvraag is opgeslagen en de maildienst heeft de werkboekmail geaccepteerd. Controleer ook je spammap. Ontvangst in je inbox is nog niet bevestigd.'+(body.proposal?' Ook je verzoek om een voorstel is opgeslagen.':'');
   requestId=crypto.randomUUID();storedBody=null;form.reset();for(const field of form.querySelectorAll('input,textarea'))field.disabled=false;document.querySelector('#help-label').hidden=true;button.textContent='Werkboek per e-mail aanvragen';
  }catch(e){if(!knownOutcome){storedBody=body;for(const field of form.querySelectorAll('input,textarea'))field.disabled=true;button.textContent='Aanvraagstatus opnieuw controleren';status.textContent='De reactie is nog niet bevestigd. De verwerking kan al gestart zijn. Probeer opnieuw; dezelfde aanvraagcode en gegevens blijven behouden.';}else status.textContent=e.message;}finally{busy=false;button.disabled=false;}
 });
})();
